### ISSUE TITLE
Windows Defender quarantines "Uninstall IGV JBrowse CircularView.exe"

### ISSUE THREAD

**Issue by gabeng** [igvteam/circular-view-app#19]
I wanted to give the new CircularView a try. After installation of 
https://igv.org/downloads/circview/IGV%20JBrowse%20CircularView%20Setup%200.1.0.exe
Windows Defender issues an alert and quarantines the uninstall exe.

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fBulta!rfn&threatid=2147694403

**Comment by jrobinso** [comment]
@qabeng. it seems others have this problem with electron apps, but not everyone (I do not for example on my Windows 10 machine).   I'm not sure what we can do about it but will continue investigating.   Are you able to run circular-view-app or does the warning re the installer block everything?

See this thread, among others. https://github.com/electron-userland/electron-builder/issues/4793

**Comment by jrobinso** [comment]
It seems this is a bug in some versions of electron-builder.   I've updated to the latest version (of electron-builder) and am rebuilding now.   Will update when ready.

**Comment by jrobinso** [comment]
@qabeng,  I've rebuilt the installer with the most recent version of "electron-builder", which reportedly fixes this issue.  I have no way to test it as it was not an issue with my Windows 10 machine.   If you could download the installer again and give it a try it would be most appreciated.   The link is the same,

https://igv.org/downloads/circview/IGV%20JBrowse%20CircularView%20Setup%200.1.0.exe

Thanks

**Comment by gabeng** [comment]
Thanks for your quick response. I am afk for today, but will try tomorrow!
